before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    binary: shopware
    ldflags: -s -w -X 'shopware-cli/cmd.version={{ .Version }}'
    flags:
      - -trimpath
    goos:
      - linux
      - windows
      - darwin

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip

release:
  github:
    owner: FriendsOfShopware
    name: shopware-cli

dockers:
  - image_templates:
      - "ghcr.io/friendsofshopware/shopware-cli:{{ .Tag }}"
      - "ghcr.io/friendsofshopware/shopware-cli:v{{ .Major }}"
      - "ghcr.io/friendsofshopware/shopware-cli:v{{ .Major }}.{{ .Minor }}"
      - "ghcr.io/friendsofshopware/shopware-cli:latest"

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

nfpms:
  -
    package_name: shopware-cli
    vendor: Shyim
    homepage: https://github.com/FriendsOfShopware/shopware-cli/
    maintainer: Shyim <github@shyim.de>
    description: A Shopware CLI
    license: MIT
    formats:
      - apk
      - deb
      - rpm

brews:
  - tap:
      owner: FriendsOfShopware
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    commit_author:
      name: Soner Sayakci
      email: s.sayakci@shopware.com
    folder: Formula
    goarm: "7"
    homepage: https://friendsofshopware.com
    description: Shopware CLI helps Shopware developers manage extensions
    license: MIT
    test: |
      system "#{bin}/shopware --version"
    dependencies:
    - name: git
    install: |-
      bin.install "shopware"