name: Update docs content

on:
  push:
    paths:
      - 'extension/config.schema.json'

jobs:
  config-schema-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Create config.schema.md
        run: |
          npm install wetzel -g
          wetzel extension/config.schema.json >> config.schema.new.md

      - name: Commit
        run: |
          git checkout docs
          git config user.name "GitHub Actions Bot"
          git config user.email "<actions@github.com>"
          rm -f config.schema.md
          mv config.schema.new.md config.schema.md
          git add -f config.schema.md
          git commit -m "chore: Update config.schema.md"
          git push