name: Update docs content

on:
  push:
    paths:
      - 'extension/config.schema.json'

jobs:
  config-schema-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Create config.schema.md
        run: |
          npm install wetzel -g
          wetzel extension/config.schema.json >> shopware-extension.yml-schema.new.md

      - uses: actions/checkout@v2
        with:
          ref: docs
          clean: false

      - name: Commit
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<actions@github.com>"
          rm -f shopware-extension.yml-schema.md
          mv shopware-extension.yml-schema.new.md shopware-extension.yml-schema.md
          git add -f shopware-extension.yml-schema.md
          git commit -m "chore: Update shopware-extension.yml-schema.md"
          git push