name: Update docs content

on:
  push:
    paths:
      - 'extension/shopware-extension-schema.json'

jobs:
  config-schema-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Create config.schema.md
        run: |
          npm install wetzel -g
          wetzel extension/shopware-extension-schema.json >> schema.new.md

      - uses: actions/checkout@v2
        with:
          ref: docs
          clean: false

      - name: Commit
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          echo -e "---\n title: 'Schema of .shopware-extensions.yml' \n---\n\n$(cat schema.new.md)" > schema.new.md
          rm -f content/docs/shopware-extensions.yml-schema/index.md
          mv schema.new.md content/docs/shopware-extensions.yml-schema/index.md
          git add -f content/docs/shopware-extensions.yml-schema/index.md
          git commit -m "chore: Update shopware-extension.yml-schema.md"
          git push